import TokenCapture from "@/components/TokenCapture";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default function TokenCaptureTest() {
  return (
    <div className="min-h-screen bg-gray-50 p-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            iPOS Token Capture Testing
          </h1>
          <p className="text-lg text-gray-600">
            Test Dejavoo iPOS token capture functionality for SaaS recurring and membership payments
          </p>
        </div>
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Token Capture Component */}
          <div>
            <TokenCapture />
          </div>
          
          {/* Information Panel */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>How Token Capture Works</CardTitle>
                <CardDescription>
                  Understanding iPOS token functionality
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">Initial Token Capture</h4>
                  <p className="text-sm text-gray-600">
                    Process a payment and capture a secure token that represents the customer's payment method.
                    This allows future charges without re-entering card details.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">Token Reuse</h4>
                  <p className="text-sm text-gray-600">
                    Use the captured token to process subsequent payments for subscriptions, memberships, 
                    or recurring billing without customer interaction.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">SaaS Integration</h4>
                  <p className="text-sm text-gray-600">
                    Perfect for SaaS applications requiring automated billing cycles, membership renewals,
                    and subscription management.
                  </p>
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Implementation Notes</CardTitle>
                <CardDescription>
                  Technical details for developers
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">Token Security</h4>
                  <p className="text-sm text-gray-600">
                    Tokens are securely generated by Dejavoo and can only be used with your merchant account.
                    They do not contain actual card data.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">Customer Management</h4>
                  <p className="text-sm text-gray-600">
                    Each token can be associated with a customer ID and subscription ID for organized 
                    recurring payment management.
                  </p>
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-gray-800">API Endpoints</h4>
                  <p className="text-sm text-gray-600">
                    • <code className="text-xs bg-gray-100 px-1 rounded">/api/payment/token-capture</code> - Capture new token<br/>
                    • <code className="text-xs bg-gray-100 px-1 rounded">/api/payment/token-reuse</code> - Use existing token
                  </p>
                </div>
              </CardContent>
            </Card>
            
            <Card>
              <CardHeader>
                <CardTitle>Test Workflow</CardTitle>
                <CardDescription>
                  Recommended testing sequence
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">1</div>
                  <p className="text-sm text-gray-700">Configure terminal settings with valid TPN and API Key</p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">2</div>
                  <p className="text-sm text-gray-700">Enter test amount and customer information</p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">3</div>
                  <p className="text-sm text-gray-700">Click "Capture Token" to process initial payment</p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-xs font-bold">4</div>
                  <p className="text-sm text-gray-700">Review captured token in the response</p>
                </div>
                <div className="flex items-center space-x-2">
                  <div className="w-6 h-6 bg-green-100 text-green-600 rounded-full flex items-center justify-center text-xs font-bold">5</div>
                  <p className="text-sm text-gray-700">Click "Test Token Reuse" to validate recurring payment</p>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </div>
  );
}