name: Build Android APK
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: npm ci

      - name: Build web assets
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      # --- CORRECTED: Single step for keystore generation script ---
      - name: Generate signing keystore (Sandbox)
        run: |
          chmod +x scripts/generate-keystore.sh
          ./scripts/generate-keystore.sh sandbox 
      # --- END CORRECTED STEP ---

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build APK
        working-directory: ./android
        # Passes the GitLab token as a project property for dependency resolution
        run: ./gradlew assembleDebug --no-daemon -DnearPayGitLabToken="${{ secrets.NEARPAY_GITLAB_TOKEN }}"
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_17_X64 }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30

      - name: Create release (on main branch push)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/debug/app-debug.apk
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
